services:
  spark-master:
    build: .
    container_name: spark-master
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8081
    ports:
      - "8081:8081"
      - "7077:7077"
    volumes:
      - ../data/spark/jars:/opt/spark/user-jars:ro
      - ../data/spark/logs:/opt/spark/spark-events
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
    restart: always

  spark-worker:
    build: .
    container_name: spark-worker
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
      PYSPARK_PYTHON: python3
    ports:
      - "8082:8082"
    volumes:
      - ../data/spark/jars:/opt/spark/user-jars:ro
      - ../data/spark/worker:/opt/spark/work
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
    depends_on:
      - spark-master
    restart: always

networks:
  default:
    external: true
    name: data-platform
